### ISSUE TITLE
Hoiw is mining calculated

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#1]
Howdy, 

No error just some info needed. I downloaded this as a test to see if I would be happy to spend some money on it, however I am not seeing how this works. The mining progress bar, does it mine when the app is active? does it mine when inactive? seems like the only time it actually shows a higher number is if I quite the app and re0launch it again, otherwise the number don't count up at all

**Comment by lainsce** [comment]
Mining happens in real time every 10 seconds of the app opened.

**Comment by selwynorren** [comment]
Thanks so much for your reply. May be good to also check mining speed when the app is closed an opened again. I was able to get to 100 units of minerals pretty quickly just by closing and opening the app
