### ISSUE TITLE
[Bug] Separator Errors

### ISSUE THREAD

**Issue by ghost** [lainsce/reganam#12]
Hi,

I believe there is an error in the separator function:
![game](https://user-images.githubusercontent.com/7816755/59899268-6d813b80-93f4-11e9-868e-fb0a28c19e04.png)

**Comment by lainsce** [comment]
This is WIP for 1.0.5

**Comment by ghost** [comment]
The error still exists in the latest version.

**Comment by lainsce** [comment]
Try resetting your game, it shouldn't happen again.
Install Dconf Editor, find your game data (kind of like registry) here:
/com/github/lainsce/reganam/ right click the item and click on reset and the :white_check_mark: in the statusbar.
