### ISSUE TITLE
[Feature Request] People & Houses

### ISSUE THREAD

**Issue by ghost** [lainsce/reganam#15]
Hi,

I nice feature could be that you need to build houses that more people can settle on your planet.
The people are needed to upgrade all buildings.
So may a info under Diameter how much settler on your planet.

**Comment by selwynorren** [comment]
I like that, sort of the amount of mines that can be built is determined by how many people are on the planet, which in turn is determined by the amount of houses

**Comment by ghost** [comment]
Yes that’s nice idea.
Thanks that you like it

**Comment by lainsce** [comment]
Couldn't go with population blockers for mine production for now.

**Comment by selwynorren** [comment]
Very nice, I like where this one is going, Thanks so much Lainsce
