### ISSUE TITLE
Cannot upgrade storage

### ISSUE THREAD

**Issue by freaktechnik** [lainsce/reganam#16]
I currently have a crystal storage capacity of 2000. If I wanted to upgrade that to level 2, the app/game wants me to spend 2100 crystal.

**Comment by freaktechnik** [comment]
...which happens because the price is 100 * mine level? Which would be fine with me if I could restart the game if I messed up like this, but since that's not a possibility I'd expect the max price to be my current storage capacity.

But maybe this is about to change either way based on what you commented on my last issue.

**Comment by lainsce** [comment]
Each level of the storages should scale like this:

| Level | Price |
| --- | --- |
| 1 | 200 (100 if Hydrogen) |
| 2 | 300 (200 if Hydrogen) |
| 3 | 400 (300 if Hydrogen) |
| 4 | 500 (400 if Hydrogen) |
| 5 | 600 (500 if Hydrogen) |
| 6 | 700 (600 if Hydrogen) |

and so on.

If that's not what's happening, then it's a bug, and I'll add to the 1.0.6 milestone.

**Comment by freaktechnik** [comment]
For me the crystal storage prices scale based on the level of the crystal miner times 100. At least the price for level 2 does.

**Comment by lainsce** [comment]
Which version are you playing?

**Comment by freaktechnik** [comment]
Latest on App Center... So 1.0.6 I think? Not currently near my machine.

**Comment by lainsce** [comment]
Ah yea, 1.0.6-ap/1.0.4.

In that one, there was a bug with the mines where they wouldn't update under new launches. It's been fixed now on 1.0.7-ap/1.0.5 hopefully. :smile:

**Comment by freaktechnik** [comment]
The problem isn't with mines though? It's the storage that is too expensive? (And yes, the storage capacity of the "over upgraded" storages resets ever launch to the level 10 one I think).

**Comment by lainsce** [comment]
The storage price scales with their level now, fixing the bug of being too expensive.
In the old build, it'd scale with the mines instead, doing the exorbitant prices.

Over-upgraded buildings and techs also aren't possible anymore in the new build.

**Comment by lainsce** [comment]
Anyhow, late game is expected to be expensive anyways.

**Comment by freaktechnik** [comment]
Just got the update with housing stuff, and the crystal storage level 2 is still too expensive.

I'd probably somehow have to trigger an update to the price?

**Comment by lainsce** [comment]
Try resetting your game with Dconf Editor, since something went wrong with the save.
Install Dconf Editor, find your game data (kind of like registry) here:
/com/github/lainsce/reganam/ right click the folder item and click on reset and the :heavy_check_mark:  in the statusbar.

**Comment by freaktechnik** [comment]
...or just `gsettings reset-recursively com.github.lainsce.reganam` - would be nice if the game offered ui for that, though! (Also yay, starting over)

**Comment by freaktechnik** [comment]
Still seeing storage prices scale by the mine level in 1.0.7/1.0.5 (you gotta fix those version numbers, especially since the app center version doesn't match the changelog in app center).

**Comment by lainsce** [comment]
I'll fix this then. Seems it slipped by me.

**Comment by lainsce** [comment]
Ought to be fixed now.
