### ISSUE TITLE
[Feature Request] Houses Research

### ISSUE THREAD

**Issue by ghost** [lainsce/reganam#19]
Hi,

maybe it should be possible that  you can research houses, too.
So that they can take more people inside.

**Comment by lainsce** [comment]
In the dock for the next version. (1.0.9)

**Comment by lainsce** [comment]
Working on this now

**Comment by ghost** [comment]
Very nice Thank you so much Am 24.06.2019 17:56 schrieb Lains <notifications@github.com>:Working on this now

**Comment by lainsce** [comment]
Done!
