### ISSUE TITLE
update_base_values not called automatically

### ISSUE THREAD

**Issue by Silberling** [lainsce/reganam#2]
* Describe the issue

The values should update very 10 seconds. They don't.

When I restart the application the values get updated (one tick).

* State what version you're using

1.0.3

**Comment by selwynorren** [comment]
Yup I have noticed this as well, each time the App loads the values get updated, however I find that the crystal value are not updating at all

**Comment by Silberling** [comment]
GTK documentation was unreachable from my location.
I **assume** Timeout.add_seconds callback requires a boolean return and will only continue if it is true. This is just guessing.

**Comment by lainsce** [comment]
It does.
