### ISSUE TITLE
[Feature Request] Detroy button

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#20]
Ability to destroy the world and create a new one. Possibly could be an addition group where you can downgrade a level

**Comment by lainsce** [comment]
I could implement a reset game button under a menu on the titlebar.

**Comment by selwynorren** [comment]
Yeah Love it!!

**Comment by lainsce** [comment]
Added!

**Comment by selwynorren** [comment]
Works like a treat, however the mining levels still show old values.

So Info Tab shows correctly, however on buildings tab and research tab it show the old values (When I click on build, then it resets the value to the correct one).

Then for the reset you essentially have two cancel options, cancel and no don't, can we do away with one of them?

**Comment by lainsce** [comment]
I can remove the "Cancel" button as well as do the other thing.

**Comment by selwynorren** [comment]
Yeah I think remove the cancel button
