### ISSUE TITLE
Helper text not showing correct data

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#21]
Howdy, just updated to the latest version and installed, the helper text on the research tab seems to no longer be accurate.

In order to research Minerals, the helper text requires 200 Crystal, 200 Hydrogen and research lab level 1, however I had all of that and it only became active once my research lab was at level 3

**Comment by lainsce** [comment]
Whoops! I may have made some mistake on the blocking of buttons or something.
Will fix soon.

**Comment by selwynorren** [comment]
lol thanks so much

**Comment by lainsce** [comment]
Fixed!
