### ISSUE TITLE
[Feature Request] Additional Infor Text on what research actually does

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#23]
I would love either an additional Button, or maybe just an expansion on teh info text about what each level does.

Info screen is pretty obvious. But it would be great to understand what impact researching a specific item has on the building speed / quantity, if there is even a relationship there ;-)

**Comment by lainsce** [comment]
On the docket for the next version as always!

**Comment by selwynorren** [comment]
lol very cool thanks so much

**Comment by lainsce** [comment]
Done!

**Comment by selwynorren** [comment]
Looks very good thanks very much
