### ISSUE TITLE
Build Storage not working as expected

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#24]
So I left the build storage alone for the beginning. Did some research lab building to level 3, Various building upgrades, but essentially left the mining to get to 1000/1000 The storage capacity was all set to 0/10.

Upgraded storage for Mineral, Crystal and Hydrogen to level one. However on the Info Page, Mineral capacity now shows 2000 (Correctly so) bu Hydrogen and Crystals still show 1000

**Comment by lainsce** [comment]
Fixed, was a minor typo.

**Comment by selwynorren** [comment]
You are awesome, thanks so much. I will test it now

**Comment by selwynorren** [comment]
I seem to still be having the same issues, Is the mineral always meant to be twice as much as the rest?

**Comment by lainsce** [comment]
It is due to the starting mineral level, I can take a thorough look though

**Comment by lainsce** [comment]
Yes, it is about the starting level. Don't worry, it isn't a bug.
