### ISSUE TITLE
[Suggestion] New Logo

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#26]
Really love this. The game looks visually awesome, yet the icon does not match the style. I don't know too much about creating icons for Elementary OS, but I have created something that could be a base-point for a new app icon.

I hope you like it.

![Reganam Logo](https://user-images.githubusercontent.com/570607/60190715-6793bc00-9833-11e9-8964-94be72b6912e.png)

**Comment by lainsce** [comment]
Yeah, I was thinking of making a new icon. It'll be a bit different than your suggestion though. :smile:

**Comment by lainsce** [comment]
Hope you like the new icon!

**Comment by selwynorren** [comment]
Very cool, thanks
