### ISSUE TITLE
[Feature Request] Periodic Saving of state

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#27]
Today we had a power failure at the office today, after boot up, all figures had return to start state, after I had built source this morning. A whole day's worth of mining gone - lol.

I also tested what would happen if I restarted without closing Reganam, even that looses all values.

Would it be possible to periodically auto save values?

**Comment by lainsce** [comment]
I'll work on this. I have a feeling that I already have done it before but it may not be working.

**Comment by selwynorren** [comment]
Awesome thanks so much. I must admit the game is working really well now, Thanks for all your efforts

**Comment by lainsce** [comment]
And it's my first foray into programming a game!

**Comment by lainsce** [comment]
This should already be a thing, maybe an external bug struck your game.
