### ISSUE TITLE
Building houses requires minerals instead of crystal and hydrogen

### ISSUE THREAD

**Issue by TvanZ** [lainsce/reganam#32]
The tooltip for building housing indicates that it requires crystal and hydrogen. However, when I build housing, only minerals are used.

I am on version 1.1.1.

I'm sorry but I don't know how to attach a screenshot.

## Hello! If you found an error in this app, follow this template:

* Use a descriptive title
* Describe the issue
* State what version you're using
* Take a screenshot of the problem, then use the Markdown property for it:  
   `![any_name_here](url_here)`
* If the problem needs it, show me a video of the problem with Screenkey running in the background.

Thanks!

**Comment by lainsce** [comment]
Fixed!

**Comment by TvanZ** [comment]
Doesn't appear to be fixed in version 1.1.2:
Housing still requires minerals (now also crystals), while tooltip indicates crystal and hydrogen.

**Comment by lainsce** [comment]
I'll look further.
