### ISSUE TITLE
Research showing 0 values on launch

### ISSUE THREAD

**Issue by selwynorren** [lainsce/reganam#6]
I cloned the repo after the last commits and everything seems to be working fine, however I have noticed a small bug.

I built a research lab, that worked fine, however when I re-launched the app, it showed that my research lab was 0/12, however it dies remember the number I had, as when I build it again, it then showed 2/12, however if I quit the game and re-launch it, again it shows 0/12.

This is true for any values on that page, so it shows all 0/12 on launch, however if I research anything it shows the correct value then

**Comment by lainsce** [comment]
I'll look into this ASAP.

**Comment by selwynorren** [comment]
Thanks so much. Really love your game!!

**Comment by lainsce** [comment]
Fixed!

**Comment by selwynorren** [comment]
You are awesome, Ill build shortly
