### ISSUE TITLE
[Bug] Can get more storage levels than the max indicated

### ISSUE THREAD

**Issue by freaktechnik** [lainsce/reganam#9]
I'm not sure if this is a misunderstanding of the game's GUI or not so here goes:
I currently have 12/10 Mineral storages. At least that's what the GUI says. I recently upgraded to 1.0.4.
![image](https://user-images.githubusercontent.com/640949/59884145-a0f1a500-93b7-11e9-974c-3d27fb435779.png)

**Comment by lainsce** [comment]
I'm on the way to implementing a planet available spaces thing, for 1.0.5.
That way, one cannot upgrade if the spaces are spent.

**Comment by lainsce** [comment]
That is, I fixed the max build level to block the buttons from being actionable.
